# Generated by Django 5.0.6 on 2024-11-01 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='permanent_address',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='present_address',
            field=models.TextField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='full_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
