# Generated by Django 5.0.6 on 2024-11-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_remove_donorprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
