# Generated by Django 5.0.6 on 2024-11-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_donorprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
