# Generated by Django 5.0.6 on 2024-11-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_siteinfor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteInfor',
            new_name='SiteInfo',
        ),
    ]
