# Generated by Django 5.0.6 on 2024-11-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_rename_siteinfor_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(default=0, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
