# Generated by Django 5.0.6 on 2024-11-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_siteinfo_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='site_facebook',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_instagram',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_pinterest',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_x',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
