# Generated by Django 5.0.6 on 2024-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_siteinfo_site_facebook_siteinfo_site_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/')),
                ('short_text_1', models.CharField(max_length=255)),
                ('short_text_2', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
