# Generated by Django 5.0.6 on 2024-11-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0016_alter_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='published_at',
        ),
    ]
