# Generated by Django 5.0.6 on 2024-11-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0017_rename_date_blog_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
