# Generated by Django 5.0.6 on 2024-11-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0019_rename_created_at_contact_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='team_members/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
